modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="trhalo"
version="1.0.0"
displayName="Trhalo"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Bram, MCreator"

[[dependencies.trhalo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



